services:
  nextjs:
    platform: linux/amd64
    build:
      context: .
      target: dev
    env_file:
      - ./.env.development
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    restart: always
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"
    networks:
      - default
      - api_grants_backend

  nextjs-prod:
    platform: linux/amd64
    build:
      context: .
      target: release
    env_file:
      - ./.env.local
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    restart: always
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:3000"
    networks:
      - default
      - api_grants_backend

  storybook:
    platform: linux/amd64
    build:
      context: .
      target: dev
    command: npm run storybook
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
      - ./.storybook:/frontend/.storybook
      - ./stories:/frontend/stories
    restart: always
    ports:
      - "${STORYBOOK_HOST_PORT:-6006}:6006"
    networks:
      - default

networks:
  api_grants_backend:
    external: true
    name: ${API_BACKEND_NETWORK_NAME:-api_grants_backend}
